# Generated by Django 3.0.4 on 2020-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('I', 'Indoor'), ('O', 'Outdoor')], max_length=200, null=True),
        ),
    ]
